model: DLR
equation: Phi41+  # Phi41+/Phi41+1
data_type: ${data_type}  # xi/u0_xi
truncation: ${truncation}  # [32,64,128,256]


data_path: '../../data_gen/results/${equation}_DLR/${equation}_${data_type}_trc${truncation}.mat'

height: 2

ntrain: 800
nval: 200
ntest: 200
batch_size: 32
epochs: 1000
learning_rate: 1e-3
weight_decay: 1e-5
print_every: 50
seed: 3407
delta: 0.0001
plateau_terminate: 100
checkpoint_file: '${data_type}_trc${truncation}.pth'

base_dir: '../result/${model}_${equation}/'