model: DLR  #确认
equation: phi42
#task: ${task}  # xi/u0xi
data_type: xi #${data_type}  # xi/u0xi/xi/u0_xi
load_cp: False #'../../u0_xi_trc64_run-joab8cp8.pth'

wandb:
  entity: "SPDE_hackathon"  #确认
  project: "${model}_${equation}"  #确认
  name: "xi"

fixed:
  data:
    data_path: '/root/autodl-tmp/SPDE_hackathon/results/Phi42+/Phi42+_reno_xi_eps_2_1200.mat'
    sub_x: 1
    T: 250
    sub_t: 5
  model:
    height: 2
#    nu: 1e-4
  train:
    ntrain: 1000
#    nval: 0
    ntest: 200
    batch_size: 64
    epochs: 1000 #500
    learning_rate: 1e-2
    weight_decay: 1e-5
    print_every: 50
    seed: 3407  #确认
    sche: 'cos'
#    delta: 0
#    plateau_terminate: 100
    checkpoint_file: '${data_type}'  #确认
  save:
    base_dir: '../result/${model}_${equation}'  #确认