model: FNO
equation: Phi41+1
task: xi  # u0/xi
data_type: xi  # u0_xi/xi
truncation: ${truncation}  # [32,64,128,256]

wandb:
  entity: "SPDE_hackathon"
  project: "${model}_${equation}"
  name: "${task}_trc${truncation}"

sweep:
  program: train1d_wb.py
  name: "${task}_trc${truncation}"
  method: grid
  metric:
    name: loss_val
    goal: minimize
  parameters:
    L:  # iter
      values: [1, 2, 3, 4]
    modes1:
      values: [16, 32]
    modes2:
      values: [16, 25]

fixed:
  data:
    data_path: '../../data_gen/examples/results/${equation}/${equation}_${data_type}_trc${truncation}.mat'
    dim_x: 128
    T: 51
    sub_t: 1
  tune_param:
    ntrain: 800
    nval: 200
    ntest: 200
    plateau_patience: 50
    plateau_terminate: 100
    checkpoint_file: '${task}_trc${truncation}'
  train_param:
    ntrain: 1000
    ntest: 200
    scheduler_step: 100
    scheduler_gamma: 0.5
  model:
    batch_size: 20
    width: 32  # d_h
    epochs: 1000
    learning_rate: 0.0025
    weight_decay: 1e-4
    delta: 0.0001
    print_every: 50
    seed: 3407
  save:
    base_dir: '../result/${model}_${equation}'
