model: FNO
equation: Phi41
data: Phi41+sigma01_u0_xi_trc128_1200

L: 1  # [1, 2, 3, 4]  # iter
modes1: 16  # [16, 32]
modes2: 16  # [16, 25]

data_path: '../../data_gen/results/${equation}/${data}.mat'
dim_x: 128
T: 51
sub_t: 1

ntrain: 840
nval: 180
ntest: 180
plateau_patience: 50
plateau_terminate: 100

#scheduler_step: 100
#scheduler_gamma: 0.5

batch_size: 20
width: 32  # d_h
epochs: 1000
learning_rate: 0.0025
weight_decay: 1e-4
delta: 0.0001
print_every: 50
seed: 3407

base_dir: '../result/${model}_${equation}'
checkpoint_file: '${data}'
