sim:
  a: 0
  b: 1.0
  Nx: 128
  s: 0
  t: 0.5
  Nt: 50  # dt=1e-2
  noise_type: ${noise_type}  # 'cylindrical', 'Q'
  truncation: ${truncation}  # sim.truncation=32,64,128,256
  sigma: 1
  fix_u0: ${fixed_u0}  # True -> fix; False -> vary
  num: 1200

seed: 42

save_dir: 'results/KdV/'
save_name: 'KdV'